name = "SteveCraft"
author = "BigSteveBig"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "583ea4ebc3a77f57d990af49126612d304fe6101706d0e2bc49cfaec5c41f2d1"

[versions]
bta = "8.0.1"
fabric = "0.18.4-bta.11"
minecraft = "b1.7.3"
unsup = "1.2.7"

[options]
acceptable-game-versions = ["b1.7.3"]
