name = "SteveCraft"
author = "BigSteveBig"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14d71d4b6ac5562cda07fbeadb7db8c7ed84f69264e343a21174cdae2e5938a6"

[versions]
bta = "8.0.1"
fabric = "0.18.4-bta.11"
minecraft = "b1.7.3"
unsup = "1.2.7"

[options]
acceptable-game-versions = ["b1.7.3"]
