name = "SteveCraft"
author = "BigSteveBig"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f4586072814a9dbe7f8f62f892fc487216ae599830fdbca4f1e424d60380117"

[versions]
bta = "8.0.1"
fabric = "0.18.4-bta.11"
minecraft = "b1.7.3"
unsup = "1.2.7"

[options]
acceptable-game-versions = ["b1.7.3"]
